"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from ajayji.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .askop import (
        AskRequestBody,
        AskRequestBodyTypedDict,
        AskResponseBody,
        AskResponseBodyTypedDict,
    )
    from .convert_modelop import (
        ConvertModelRequestBody,
        ConvertModelRequestBodyTypedDict,
    )
    from .create_databaseop import (
        CreateDatabaseRequestBody,
        CreateDatabaseRequestBodyTypedDict,
        CreateDatabaseResponseBody,
        CreateDatabaseResponseBodyTypedDict,
    )
    from .create_personaop import (
        CreatePersonaRequestBody,
        CreatePersonaRequestBodyTypedDict,
        CreatePersonaResponseBody,
        CreatePersonaResponseBodyTypedDict,
    )
    from .create_vector_dbop import (
        CreateVectorDbRequestBody,
        CreateVectorDbRequestBodyTypedDict,
        CreateVectorDbResponseBody,
        CreateVectorDbResponseBodyTypedDict,
    )
    from .execute_toolop import ExecuteToolRequestBody, ExecuteToolRequestBodyTypedDict
    from .invoke_personaop import (
        InvokePersonaRequest,
        InvokePersonaRequestTypedDict,
        InvokePersonaResponseBody,
        InvokePersonaResponseBodyTypedDict,
    )
    from .load_modelop import (
        LoadModelRequestBody,
        LoadModelRequestBodyTypedDict,
        LoadModelResponseBody,
        LoadModelResponseBodyTypedDict,
    )
    from .post_api_v1_mcp_connectop import (
        PostAPIV1McpConnectRequestBody,
        PostAPIV1McpConnectRequestBodyTypedDict,
        PostAPIV1McpConnectResponseBody,
        PostAPIV1McpConnectResponseBodyTypedDict,
    )
    from .post_api_v1_mcp_disconnectop import (
        PostAPIV1McpDisconnectResponseBody,
        PostAPIV1McpDisconnectResponseBodyTypedDict,
    )
    from .pull_modelop import (
        PullModelRequestBody,
        PullModelRequestBodyTypedDict,
        PullModelResponseBody,
        PullModelResponseBodyTypedDict,
    )
    from .stop_modelop import StopModelResponseBody, StopModelResponseBodyTypedDict

__all__ = [
    "AskRequestBody",
    "AskRequestBodyTypedDict",
    "AskResponseBody",
    "AskResponseBodyTypedDict",
    "ConvertModelRequestBody",
    "ConvertModelRequestBodyTypedDict",
    "CreateDatabaseRequestBody",
    "CreateDatabaseRequestBodyTypedDict",
    "CreateDatabaseResponseBody",
    "CreateDatabaseResponseBodyTypedDict",
    "CreatePersonaRequestBody",
    "CreatePersonaRequestBodyTypedDict",
    "CreatePersonaResponseBody",
    "CreatePersonaResponseBodyTypedDict",
    "CreateVectorDbRequestBody",
    "CreateVectorDbRequestBodyTypedDict",
    "CreateVectorDbResponseBody",
    "CreateVectorDbResponseBodyTypedDict",
    "ExecuteToolRequestBody",
    "ExecuteToolRequestBodyTypedDict",
    "InvokePersonaRequest",
    "InvokePersonaRequestTypedDict",
    "InvokePersonaResponseBody",
    "InvokePersonaResponseBodyTypedDict",
    "LoadModelRequestBody",
    "LoadModelRequestBodyTypedDict",
    "LoadModelResponseBody",
    "LoadModelResponseBodyTypedDict",
    "PostAPIV1McpConnectRequestBody",
    "PostAPIV1McpConnectRequestBodyTypedDict",
    "PostAPIV1McpConnectResponseBody",
    "PostAPIV1McpConnectResponseBodyTypedDict",
    "PostAPIV1McpDisconnectResponseBody",
    "PostAPIV1McpDisconnectResponseBodyTypedDict",
    "PullModelRequestBody",
    "PullModelRequestBodyTypedDict",
    "PullModelResponseBody",
    "PullModelResponseBodyTypedDict",
    "StopModelResponseBody",
    "StopModelResponseBodyTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AskRequestBody": ".askop",
    "AskRequestBodyTypedDict": ".askop",
    "AskResponseBody": ".askop",
    "AskResponseBodyTypedDict": ".askop",
    "ConvertModelRequestBody": ".convert_modelop",
    "ConvertModelRequestBodyTypedDict": ".convert_modelop",
    "CreateDatabaseRequestBody": ".create_databaseop",
    "CreateDatabaseRequestBodyTypedDict": ".create_databaseop",
    "CreateDatabaseResponseBody": ".create_databaseop",
    "CreateDatabaseResponseBodyTypedDict": ".create_databaseop",
    "CreatePersonaRequestBody": ".create_personaop",
    "CreatePersonaRequestBodyTypedDict": ".create_personaop",
    "CreatePersonaResponseBody": ".create_personaop",
    "CreatePersonaResponseBodyTypedDict": ".create_personaop",
    "CreateVectorDbRequestBody": ".create_vector_dbop",
    "CreateVectorDbRequestBodyTypedDict": ".create_vector_dbop",
    "CreateVectorDbResponseBody": ".create_vector_dbop",
    "CreateVectorDbResponseBodyTypedDict": ".create_vector_dbop",
    "ExecuteToolRequestBody": ".execute_toolop",
    "ExecuteToolRequestBodyTypedDict": ".execute_toolop",
    "InvokePersonaRequest": ".invoke_personaop",
    "InvokePersonaRequestTypedDict": ".invoke_personaop",
    "InvokePersonaResponseBody": ".invoke_personaop",
    "InvokePersonaResponseBodyTypedDict": ".invoke_personaop",
    "LoadModelRequestBody": ".load_modelop",
    "LoadModelRequestBodyTypedDict": ".load_modelop",
    "LoadModelResponseBody": ".load_modelop",
    "LoadModelResponseBodyTypedDict": ".load_modelop",
    "PostAPIV1McpConnectRequestBody": ".post_api_v1_mcp_connectop",
    "PostAPIV1McpConnectRequestBodyTypedDict": ".post_api_v1_mcp_connectop",
    "PostAPIV1McpConnectResponseBody": ".post_api_v1_mcp_connectop",
    "PostAPIV1McpConnectResponseBodyTypedDict": ".post_api_v1_mcp_connectop",
    "PostAPIV1McpDisconnectResponseBody": ".post_api_v1_mcp_disconnectop",
    "PostAPIV1McpDisconnectResponseBodyTypedDict": ".post_api_v1_mcp_disconnectop",
    "PullModelRequestBody": ".pull_modelop",
    "PullModelRequestBodyTypedDict": ".pull_modelop",
    "PullModelResponseBody": ".pull_modelop",
    "PullModelResponseBodyTypedDict": ".pull_modelop",
    "StopModelResponseBody": ".stop_modelop",
    "StopModelResponseBodyTypedDict": ".stop_modelop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
