"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ConvertModelRequestBodyTypedDict(TypedDict):
    input_mapping: str
    r"""The name of the input tensor/layer."""
    name: str
    r"""Name to register the resulting tool as."""
    output_mapping: str
    r"""The name of the output tensor/layer."""
    source_file_path: str
    r"""Absolute path to the source model file."""
    type: str
    r"""The type of model (e.g., 'image', 'text')."""
    height: NotRequired[Nullable[int]]
    r"""Target height for image models."""
    width: NotRequired[Nullable[int]]
    r"""Target width for image models."""


class ConvertModelRequestBody(BaseModel):
    input_mapping: str
    r"""The name of the input tensor/layer."""

    name: str
    r"""Name to register the resulting tool as."""

    output_mapping: str
    r"""The name of the output tensor/layer."""

    source_file_path: str
    r"""Absolute path to the source model file."""

    type: str
    r"""The type of model (e.g., 'image', 'text')."""

    height: OptionalNullable[int] = UNSET
    r"""Target height for image models."""

    width: OptionalNullable[int] = UNSET
    r"""Target width for image models."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["height", "width"])
        nullable_fields = set(["height", "width"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
