"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreatePersonaRequestBodyTypedDict(TypedDict):
    agent_id: str
    r"""The unique ID for this Persona."""
    agent_name: str
    r"""The human-readable name of the Persona."""
    model: str
    r"""The filename of the LLM to use (e.g., llama-3-8b.gguf)."""
    mcp_servers: NotRequired[List[str]]
    r"""A list of MCP Server SSE URIs (e.g., http://127.0.0.1:8000/sse) to connect to during orchestration."""
    system_prompt: NotRequired[Nullable[str]]
    r"""Optional system prompt to override the default."""


class CreatePersonaRequestBody(BaseModel):
    agent_id: str
    r"""The unique ID for this Persona."""

    agent_name: str
    r"""The human-readable name of the Persona."""

    model: str
    r"""The filename of the LLM to use (e.g., llama-3-8b.gguf)."""

    mcp_servers: Optional[List[str]] = None
    r"""A list of MCP Server SSE URIs (e.g., http://127.0.0.1:8000/sse) to connect to during orchestration."""

    system_prompt: OptionalNullable[str] = UNSET
    r"""Optional system prompt to override the default."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mcp_servers", "system_prompt"])
        nullable_fields = set(["system_prompt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CreatePersonaResponseBodyTypedDict(TypedDict):
    r"""Persona created/updated successfully"""

    status: NotRequired[str]


class CreatePersonaResponseBody(BaseModel):
    r"""Persona created/updated successfully"""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
