"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateVectorDbRequestBodyTypedDict(TypedDict):
    folder_path: str
    r"""The absolute file path to the folder containing documents to index."""
    name: str
    r"""The human-readable name of the new vector DB tool."""


class CreateVectorDbRequestBody(BaseModel):
    folder_path: str
    r"""The absolute file path to the folder containing documents to index."""

    name: str
    r"""The human-readable name of the new vector DB tool."""


class CreateVectorDbResponseBodyTypedDict(TypedDict):
    r"""Vector DB created successfully"""

    status: NotRequired[str]


class CreateVectorDbResponseBody(BaseModel):
    r"""Vector DB created successfully"""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
