"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class ExecuteToolRequestBodyTypedDict(TypedDict):
    tool_name: str
    r"""The registered name of the tool to execute."""
    args: NotRequired[Dict[str, Any]]
    r"""A JSON object containing the arguments required by the tool."""


class ExecuteToolRequestBody(BaseModel):
    tool_name: str
    r"""The registered name of the tool to execute."""

    args: Optional[Dict[str, Any]] = None
    r"""A JSON object containing the arguments required by the tool."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["args"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
