"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel
from ajayji.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPersonaCanvasRequestTypedDict(TypedDict):
    id: str
    r"""The ID of the persona to generate the canvas for"""


class GetPersonaCanvasRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the persona to generate the canvas for"""
