"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel, UNSET_SENTINEL
from ajayji.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InvokePersonaRequestTypedDict(TypedDict):
    request_body: Dict[str, Any]
    id: str
    r"""The unique ID of the ChatPersona to invoke."""


class InvokePersonaRequest(BaseModel):
    request_body: Annotated[
        Dict[str, Any],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique ID of the ChatPersona to invoke."""


class InvokePersonaResponseBodyTypedDict(TypedDict):
    r"""Successful workflow execution"""

    response: NotRequired[Dict[str, Any]]
    r"""The final parsed output from the Persona's output_parser script."""


class InvokePersonaResponseBody(BaseModel):
    r"""Successful workflow execution"""

    response: Optional[Dict[str, Any]] = None
    r"""The final parsed output from the Persona's output_parser script."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["response"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
