"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ajayji.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TestParserRequestBodyTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    raw_input: str
    r"""The raw string (usually JSON) to feed into the parser."""
    script: str
    r"""The raw Javascript containing a `parse(rawInput)` function."""


class TestParserRequestBody(BaseModel):
    __test__ = False

    raw_input: str
    r"""The raw string (usually JSON) to feed into the parser."""

    script: str
    r"""The raw Javascript containing a `parse(rawInput)` function."""


class TestParserResponseBodyTypedDict(TypedDict):
    r"""The parsed output and execution logs."""

    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    logs: NotRequired[List[str]]
    result: NotRequired[str]


class TestParserResponseBody(BaseModel):
    r"""The parsed output and execution logs."""

    __test__ = False

    logs: Optional[List[str]] = None

    result: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["logs", "result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
