"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from ajayji import errors, models, utils
from ajayji._hooks import HookContext
from ajayji.types import OptionalNullable, UNSET
from ajayji.utils.unmarshal_json_response import unmarshal_json_response
import httpx
from typing import Any, Dict, List, Mapping, Optional


class PersonaOrchestration(BaseSDK):
    def create_persona(
        self,
        *,
        agent_id: str,
        agent_name: str,
        model: str,
        embedding_model_name: OptionalNullable[str] = UNSET,
        enable_chat: OptionalNullable[bool] = UNSET,
        enable_webhook: OptionalNullable[bool] = UNSET,
        global_events: OptionalNullable[List[str]] = UNSET,
        input_parser_id: OptionalNullable[str] = UNSET,
        input_topic: OptionalNullable[str] = UNSET,
        mcp_servers: Optional[List[str]] = None,
        output_parser_id: OptionalNullable[str] = UNSET,
        output_topic: OptionalNullable[str] = UNSET,
        system_prompt: OptionalNullable[str] = UNSET,
        tool_call_parser_id: OptionalNullable[str] = UNSET,
        tool_ids: OptionalNullable[List[str]] = UNSET,
        tool_response_parser_id: OptionalNullable[str] = UNSET,
        vector_store_name: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CreatePersonaResponseBody:
        r"""Create or Update a Persona

        Creates a new Persona or updates an existing one, optionally registering MCP servers for bi-directional tool execution.

        :param agent_id: The unique ID for this Persona.
        :param agent_name: The human-readable name of the Persona.
        :param model: The filename of the LLM to use (e.g., llama-3-8b.gguf).
        :param embedding_model_name: The name of the associated Embedding Model.
        :param enable_chat: Whether the chat interface is enabled for this persona.
        :param enable_webhook: Whether the webhook interface is enabled for this persona.
        :param global_events: Array of Global Event Trigger IDs associated with this persona.
        :param input_parser_id: The ID of the Javascript parser for incoming data.
        :param input_topic: The async message queue topic for inbound messages.
        :param mcp_servers: A list of MCP Server SSE URIs (e.g., http://127.0.0.1:8000/sse) to connect to during orchestration.
        :param output_parser_id: The ID of the Javascript parser for outgoing data.
        :param output_topic: The async message queue topic for outbound messages.
        :param system_prompt: Optional system prompt to override the default.
        :param tool_call_parser_id: The ID of the Javascript parser for modifying tool calls.
        :param tool_ids: Array of Standalone Tool IDs associated with this persona.
        :param tool_response_parser_id: The ID of the Javascript parser for modifying tool responses.
        :param vector_store_name: The name of the associated Vector Store database.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreatePersonaRequestBody(
            agent_id=agent_id,
            agent_name=agent_name,
            embedding_model_name=embedding_model_name,
            enable_chat=enable_chat,
            enable_webhook=enable_webhook,
            global_events=global_events,
            input_parser_id=input_parser_id,
            input_topic=input_topic,
            mcp_servers=mcp_servers,
            model=model,
            output_parser_id=output_parser_id,
            output_topic=output_topic,
            system_prompt=system_prompt,
            tool_call_parser_id=tool_call_parser_id,
            tool_ids=tool_ids,
            tool_response_parser_id=tool_response_parser_id,
            vector_store_name=vector_store_name,
        )

        req = self._build_request(
            method="POST",
            path="/api/v1/personas",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.CreatePersonaRequestBody
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create_persona",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CreatePersonaResponseBody, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def create_persona_async(
        self,
        *,
        agent_id: str,
        agent_name: str,
        model: str,
        embedding_model_name: OptionalNullable[str] = UNSET,
        enable_chat: OptionalNullable[bool] = UNSET,
        enable_webhook: OptionalNullable[bool] = UNSET,
        global_events: OptionalNullable[List[str]] = UNSET,
        input_parser_id: OptionalNullable[str] = UNSET,
        input_topic: OptionalNullable[str] = UNSET,
        mcp_servers: Optional[List[str]] = None,
        output_parser_id: OptionalNullable[str] = UNSET,
        output_topic: OptionalNullable[str] = UNSET,
        system_prompt: OptionalNullable[str] = UNSET,
        tool_call_parser_id: OptionalNullable[str] = UNSET,
        tool_ids: OptionalNullable[List[str]] = UNSET,
        tool_response_parser_id: OptionalNullable[str] = UNSET,
        vector_store_name: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CreatePersonaResponseBody:
        r"""Create or Update a Persona

        Creates a new Persona or updates an existing one, optionally registering MCP servers for bi-directional tool execution.

        :param agent_id: The unique ID for this Persona.
        :param agent_name: The human-readable name of the Persona.
        :param model: The filename of the LLM to use (e.g., llama-3-8b.gguf).
        :param embedding_model_name: The name of the associated Embedding Model.
        :param enable_chat: Whether the chat interface is enabled for this persona.
        :param enable_webhook: Whether the webhook interface is enabled for this persona.
        :param global_events: Array of Global Event Trigger IDs associated with this persona.
        :param input_parser_id: The ID of the Javascript parser for incoming data.
        :param input_topic: The async message queue topic for inbound messages.
        :param mcp_servers: A list of MCP Server SSE URIs (e.g., http://127.0.0.1:8000/sse) to connect to during orchestration.
        :param output_parser_id: The ID of the Javascript parser for outgoing data.
        :param output_topic: The async message queue topic for outbound messages.
        :param system_prompt: Optional system prompt to override the default.
        :param tool_call_parser_id: The ID of the Javascript parser for modifying tool calls.
        :param tool_ids: Array of Standalone Tool IDs associated with this persona.
        :param tool_response_parser_id: The ID of the Javascript parser for modifying tool responses.
        :param vector_store_name: The name of the associated Vector Store database.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreatePersonaRequestBody(
            agent_id=agent_id,
            agent_name=agent_name,
            embedding_model_name=embedding_model_name,
            enable_chat=enable_chat,
            enable_webhook=enable_webhook,
            global_events=global_events,
            input_parser_id=input_parser_id,
            input_topic=input_topic,
            mcp_servers=mcp_servers,
            model=model,
            output_parser_id=output_parser_id,
            output_topic=output_topic,
            system_prompt=system_prompt,
            tool_call_parser_id=tool_call_parser_id,
            tool_ids=tool_ids,
            tool_response_parser_id=tool_response_parser_id,
            vector_store_name=vector_store_name,
        )

        req = self._build_request_async(
            method="POST",
            path="/api/v1/personas",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.CreatePersonaRequestBody
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create_persona",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CreatePersonaResponseBody, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def get_persona_canvas(
        self,
        *,
        id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> httpx.Response:
        r"""Get the Canvas Graphic

        Returns a generated PNG image of the persona's orchestration canvas.

        :param id: The ID of the persona to generate the canvas for
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPersonaCanvasRequest(
            id=id,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/personas/{id}/canvas.png",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="image/png",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_persona_canvas",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            stream=True,
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "image/png"):
            return http_res
        if utils.match_response(http_res, ["404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        http_res_text = utils.stream_to_text(http_res)
        raise errors.SDKDefaultError(
            "Unexpected response received", http_res, http_res_text
        )

    async def get_persona_canvas_async(
        self,
        *,
        id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> httpx.Response:
        r"""Get the Canvas Graphic

        Returns a generated PNG image of the persona's orchestration canvas.

        :param id: The ID of the persona to generate the canvas for
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPersonaCanvasRequest(
            id=id,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/personas/{id}/canvas.png",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="image/png",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_persona_canvas",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            stream=True,
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "image/png"):
            return http_res
        if utils.match_response(http_res, ["404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        http_res_text = await utils.stream_to_text_async(http_res)
        raise errors.SDKDefaultError(
            "Unexpected response received", http_res, http_res_text
        )

    def invoke_persona(
        self,
        *,
        id: str,
        request_body: Dict[str, Any],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.InvokePersonaResponseBody:
        r"""Invoke a Persona Webhook

        Executes a full orchestration pipeline (Tools, JS Parsers, CoreML) for a specific Persona using a JSON payload.

        :param id: The unique ID of the ChatPersona to invoke.
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.InvokePersonaRequest(
            id=id,
            request_body=request_body,
        )

        req = self._build_request(
            method="POST",
            path="/api/v1/personas/{id}/invoke",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body, False, False, "json", Dict[str, Any]
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="invoke_persona",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.InvokePersonaResponseBody, http_res)
        if utils.match_response(http_res, ["400", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def invoke_persona_async(
        self,
        *,
        id: str,
        request_body: Dict[str, Any],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.InvokePersonaResponseBody:
        r"""Invoke a Persona Webhook

        Executes a full orchestration pipeline (Tools, JS Parsers, CoreML) for a specific Persona using a JSON payload.

        :param id: The unique ID of the ChatPersona to invoke.
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.InvokePersonaRequest(
            id=id,
            request_body=request_body,
        )

        req = self._build_request_async(
            method="POST",
            path="/api/v1/personas/{id}/invoke",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body, False, False, "json", Dict[str, Any]
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="invoke_persona",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.InvokePersonaResponseBody, http_res)
        if utils.match_response(http_res, ["400", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def display(self, id: str):
        """
        Helper method to fetch the canvas PNG and display it inline in a Jupyter Notebook.
        """
        try:
            from IPython.display import display as ipython_display, Image
            
            res = self.get_persona_canvas(id=id)
            if res.status_code == 200:
                res.read()  # Explicitly read the streaming response
                ipython_display(Image(data=res.content, format='png'))
            else:
                res.read()
                print(f"Failed to load canvas: {res.status_code} - {res.text}")
        except ImportError:
            print("IPython is required to display images inline.")
            
    async def display_async(self, id: str):
        """
        Async helper method to fetch the canvas PNG and display it inline in a Jupyter Notebook.
        """
        try:
            from IPython.display import display as ipython_display, Image
            
            res = await self.get_persona_canvas_async(id=id)
            if res.status_code == 200:
                await res.aread()  # Explicitly read the async streaming response
                ipython_display(Image(data=res.content, format='png'))
            else:
                await res.aread()
                print(f"Failed to load canvas: {res.status_code} - {res.text}")
        except ImportError:
            print("IPython is required to display images inline.")