"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from openapi.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .askop import (
        AskRequest,
        AskRequestTypedDict,
        AskResponse,
        AskResponseTypedDict,
    )
    from .create_databaseop import (
        CreateDatabaseRequest,
        CreateDatabaseRequestTypedDict,
        CreateDatabaseResponse,
        CreateDatabaseResponseTypedDict,
    )
    from .invoke_personaop import (
        InvokePersonaRequest,
        InvokePersonaRequestTypedDict,
        InvokePersonaResponse,
        InvokePersonaResponseTypedDict,
    )
    from .load_modelop import (
        LoadModelRequest,
        LoadModelRequestTypedDict,
        LoadModelResponse,
        LoadModelResponseTypedDict,
    )
    from .pull_modelop import (
        PullModelRequest,
        PullModelRequestTypedDict,
        PullModelResponse,
        PullModelResponseTypedDict,
    )
    from .stop_modelop import StopModelResponse, StopModelResponseTypedDict

__all__ = [
    "AskRequest",
    "AskRequestTypedDict",
    "AskResponse",
    "AskResponseTypedDict",
    "CreateDatabaseRequest",
    "CreateDatabaseRequestTypedDict",
    "CreateDatabaseResponse",
    "CreateDatabaseResponseTypedDict",
    "InvokePersonaRequest",
    "InvokePersonaRequestTypedDict",
    "InvokePersonaResponse",
    "InvokePersonaResponseTypedDict",
    "LoadModelRequest",
    "LoadModelRequestTypedDict",
    "LoadModelResponse",
    "LoadModelResponseTypedDict",
    "PullModelRequest",
    "PullModelRequestTypedDict",
    "PullModelResponse",
    "PullModelResponseTypedDict",
    "StopModelResponse",
    "StopModelResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AskRequest": ".askop",
    "AskRequestTypedDict": ".askop",
    "AskResponse": ".askop",
    "AskResponseTypedDict": ".askop",
    "CreateDatabaseRequest": ".create_databaseop",
    "CreateDatabaseRequestTypedDict": ".create_databaseop",
    "CreateDatabaseResponse": ".create_databaseop",
    "CreateDatabaseResponseTypedDict": ".create_databaseop",
    "InvokePersonaRequest": ".invoke_personaop",
    "InvokePersonaRequestTypedDict": ".invoke_personaop",
    "InvokePersonaResponse": ".invoke_personaop",
    "InvokePersonaResponseTypedDict": ".invoke_personaop",
    "LoadModelRequest": ".load_modelop",
    "LoadModelRequestTypedDict": ".load_modelop",
    "LoadModelResponse": ".load_modelop",
    "LoadModelResponseTypedDict": ".load_modelop",
    "PullModelRequest": ".pull_modelop",
    "PullModelRequestTypedDict": ".pull_modelop",
    "PullModelResponse": ".pull_modelop",
    "PullModelResponseTypedDict": ".pull_modelop",
    "StopModelResponse": ".stop_modelop",
    "StopModelResponseTypedDict": ".stop_modelop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
