"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LoadModelRequestTypedDict(TypedDict):
    file_name: str
    r"""The filename of the model (e.g. `llama-3-8b.gguf`)."""


class LoadModelRequest(BaseModel):
    file_name: Annotated[str, pydantic.Field(alias="fileName")]
    r"""The filename of the model (e.g. `llama-3-8b.gguf`)."""


class LoadModelResponseTypedDict(TypedDict):
    r"""Model loaded successfully"""

    status: NotRequired[str]


class LoadModelResponse(BaseModel):
    r"""Model loaded successfully"""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    LoadModelRequest.model_rebuild()
except NameError:
    pass
