"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PullModelRequestTypedDict(TypedDict):
    repo: str
    r"""The Hugging Face repository (e.g., `unsloth/gemma-2b`)."""
    file_name: str
    r"""The exact filename to download (e.g., `model.gguf`)."""
    huggingface_config_id: NotRequired[Nullable[str]]
    r"""Optional ID for an authenticated Hugging Face token."""


class PullModelRequest(BaseModel):
    repo: str
    r"""The Hugging Face repository (e.g., `unsloth/gemma-2b`)."""

    file_name: Annotated[str, pydantic.Field(alias="fileName")]
    r"""The exact filename to download (e.g., `model.gguf`)."""

    huggingface_config_id: OptionalNullable[str] = UNSET
    r"""Optional ID for an authenticated Hugging Face token."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["huggingface_config_id"])
        nullable_fields = set(["huggingface_config_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PullModelResponseTypedDict(TypedDict):
    r"""Download started successfully"""

    status: NotRequired[str]


class PullModelResponse(BaseModel):
    r"""Download started successfully"""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PullModelRequest.model_rebuild()
except NameError:
    pass
