"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from ajayji_sdk_test.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .askop import (
        AskRequestBody,
        AskRequestBodyTypedDict,
        AskResponseBody,
        AskResponseBodyTypedDict,
    )
    from .create_databaseop import (
        CreateDatabaseRequestBody,
        CreateDatabaseRequestBodyTypedDict,
        CreateDatabaseResponseBody,
        CreateDatabaseResponseBodyTypedDict,
    )
    from .invoke_personaop import (
        InvokePersonaRequest,
        InvokePersonaRequestTypedDict,
        InvokePersonaResponseBody,
        InvokePersonaResponseBodyTypedDict,
    )
    from .load_modelop import (
        LoadModelRequestBody,
        LoadModelRequestBodyTypedDict,
        LoadModelResponseBody,
        LoadModelResponseBodyTypedDict,
    )
    from .pull_modelop import (
        PullModelRequestBody,
        PullModelRequestBodyTypedDict,
        PullModelResponseBody,
        PullModelResponseBodyTypedDict,
    )
    from .stop_modelop import StopModelResponseBody, StopModelResponseBodyTypedDict

__all__ = [
    "AskRequestBody",
    "AskRequestBodyTypedDict",
    "AskResponseBody",
    "AskResponseBodyTypedDict",
    "CreateDatabaseRequestBody",
    "CreateDatabaseRequestBodyTypedDict",
    "CreateDatabaseResponseBody",
    "CreateDatabaseResponseBodyTypedDict",
    "InvokePersonaRequest",
    "InvokePersonaRequestTypedDict",
    "InvokePersonaResponseBody",
    "InvokePersonaResponseBodyTypedDict",
    "LoadModelRequestBody",
    "LoadModelRequestBodyTypedDict",
    "LoadModelResponseBody",
    "LoadModelResponseBodyTypedDict",
    "PullModelRequestBody",
    "PullModelRequestBodyTypedDict",
    "PullModelResponseBody",
    "PullModelResponseBodyTypedDict",
    "StopModelResponseBody",
    "StopModelResponseBodyTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AskRequestBody": ".askop",
    "AskRequestBodyTypedDict": ".askop",
    "AskResponseBody": ".askop",
    "AskResponseBodyTypedDict": ".askop",
    "CreateDatabaseRequestBody": ".create_databaseop",
    "CreateDatabaseRequestBodyTypedDict": ".create_databaseop",
    "CreateDatabaseResponseBody": ".create_databaseop",
    "CreateDatabaseResponseBodyTypedDict": ".create_databaseop",
    "InvokePersonaRequest": ".invoke_personaop",
    "InvokePersonaRequestTypedDict": ".invoke_personaop",
    "InvokePersonaResponseBody": ".invoke_personaop",
    "InvokePersonaResponseBodyTypedDict": ".invoke_personaop",
    "LoadModelRequestBody": ".load_modelop",
    "LoadModelRequestBodyTypedDict": ".load_modelop",
    "LoadModelResponseBody": ".load_modelop",
    "LoadModelResponseBodyTypedDict": ".load_modelop",
    "PullModelRequestBody": ".pull_modelop",
    "PullModelRequestBodyTypedDict": ".pull_modelop",
    "PullModelResponseBody": ".pull_modelop",
    "PullModelResponseBodyTypedDict": ".pull_modelop",
    "StopModelResponseBody": ".stop_modelop",
    "StopModelResponseBodyTypedDict": ".stop_modelop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
